Feature/7426 aca infra
Ensono/stacks-infrastructure-aca pull request #1
Opened 2024-07-04 11:05 UTC by satenderrathee

📲 What
Created new project for Azure Container Apps.
Created Azure Container Apps using module.
Added a sample application and enabled its deployment.
The deployment of ACA using Terraform with Ensono Independent Runner (EIR).

🤔 Why
Stack cycle 14
7294- Create Azure Container Apps Terraform module

🛠 How
Added new project for Azure Container Apps, used terraform module to provision ACA and enable its deployment using Independent Runner.

👀 Evidence
Pipeline:
![image](https://github.com/Ensono/stacks-infrastructure-aca/assets/88006547/4f5a2626-f0a5-44d3-a705-e94c6ad13688)

![image](https://github.com/Ensono/stacks-infrastructure-aca/assets/88006547/9280f339-1918-4c28-82d9-facdbb675cb4)

![image](https://github.com/Ensono/stacks-infrastructure-aca/assets/88006547/5cfbc513-064f-4187-8687-5711a24a746b)

2024-07-08 10:07 UTC, danEnsono requested changes
Good overall work, some rethinking required around directory structure and redundant variable files. Lots of left over comments to remove and a few lock files.

Needs some decent documentation within the repo to support the feature outlining:
Why are we doing this feature?
How do you use this feature?
What is the pipeline doing?
What are the tests doing?

2024-07-08 10:07 UTC, danEnsono commented on src/terraform/data.tf
I think all of this terraform should still be in the `deploy\terraform` directory, perhaps under a different folder such as `additional-infra` with your primary terraform referenced as `base-infra`. That way we aren't spreading the deployment code out and it remains in the places pre-defined for deployment type code.

2024-07-08 10:07 UTC, danEnsono commented on src/terraform/data.tf
> +  resource_group_name = var.acr_rg #"aca-test-rg"  module.default_label.id
Remove comments

2024-07-08 10:07 UTC, danEnsono commented on src/terraform/locals.tf
I think all of this terraform should still be in the `deploy\terraform` directory, perhaps under a different folder such as `additional-infra` with your primary terraform referenced as `base-infra`. That way we aren't spreading the deployment code out and it remains in the places pre-defined for deployment type code.

2024-07-08 10:07 UTC, danEnsono commented on src/terraform/main.tf
I think all of this terraform should still be in the `deploy\terraform` directory, perhaps under a different folder such as `additional-infra` with your primary terraform referenced as `base-infra`. That way we aren't spreading the deployment code out and it remains in the places pre-defined for deployment type code.

2024-07-08 10:07 UTC, danEnsono commented on src/terraform/outputs.tf
I think all of this terraform should still be in the `deploy\terraform` directory, perhaps under a different folder such as `additional-infra` with your primary terraform referenced as `base-infra`. That way we aren't spreading the deployment code out and it remains in the places pre-defined for deployment type code.

2024-07-08 10:07 UTC, danEnsono commented on src/terraform/provider.tf
I think all of this terraform should still be in the `deploy\terraform` directory, perhaps under a different folder such as `additional-infra` with your primary terraform referenced as `base-infra`. That way we aren't spreading the deployment code out and it remains in the places pre-defined for deployment type code.

2024-07-08 10:07 UTC, danEnsono commented on src/terraform/variables.tf
I think all of this terraform should still be in the `deploy\terraform` directory, perhaps under a different folder such as `additional-infra` with your primary terraform referenced as `base-infra`. That way we aren't spreading the deployment code out and it remains in the places pre-defined for deployment type code.

2024-07-08 10:07 UTC, danEnsono commented on taskctl.yaml
> +  #       - infra:destroy:plan
Remove this

2024-07-08 10:07 UTC, danEnsono commented on taskctl.yaml
> +  #       - debug:env
Remove this

2024-07-08 10:07 UTC, danEnsono commented on taskctl.yaml
> +    - task: debug
Do you always want to run debug for build:container task?

2024-07-08 10:24 UTC, satenderrathee commented on src/terraform/variables.tf
These are App specific Infra , so kept under app, we have used the same approach in stack data project as well. I have mentioned that in agreed ADR as well https://amidodevelopment.atlassian.net/wiki/spaces/TEC/pages/edit-v2/4508418074?draftShareId=74f0c4c4-0ebf-4e5b-94bf-e99d8d8403dd.

2024-07-08 10:24 UTC, satenderrathee commented on src/terraform/provider.tf
These are App specific Infra , so kept under app, we have used the same approach in stack data project as well. I have mentioned that in agreed ADR as well https://amidodevelopment.atlassian.net/wiki/spaces/TEC/pages/edit-v2/4508418074?draftShareId=74f0c4c4-0ebf-4e5b-94bf-e99d8d8403dd.

2024-07-08 10:27 UTC, satenderrathee commented on taskctl.yaml
> +    - task: debug
updated.

2024-07-08 10:27 UTC, satenderrathee commented on taskctl.yaml
> +  #       - debug:env
removed

2024-07-08 10:28 UTC, satenderrathee commented on taskctl.yaml
> +  #       - infra:destroy:plan
removed

2024-07-08 11:31 UTC, satenderrathee commented on cicd/build/azDevOps/azure/deploy-infrastructure.yml
> +                    #         AZURE_TENANT_ID: $(azure-tenant-id)
removed

2024-07-08 11:32 UTC, satenderrathee commented on cicd/build/azDevOps/azure/infrastructure-aca-vars.yml
> +    value: "$(Agent.BuildDirectory)/s/$(self_repo)"
added required variables in  pipeline-vars.yml

2024-07-08 11:32 UTC, satenderrathee commented on cicd/build/azDevOps/azure/pipeline-vars.template.yml
> +    value: core
removed

2024-07-08 11:32 UTC, satenderrathee commented on cicd/build/azDevOps/azure/pipeline-vars.template.yml
> +  #   value: $(company)
uncommented

2024-07-08 11:33 UTC, satenderrathee commented on cicd/build/azDevOps/azure/pipeline-vars.template.yml
> +    value: {}
removed

2024-07-08 11:33 UTC, satenderrathee commented on cicd/build/azDevOps/azure/pipeline-vars.template.yml
> +    value: 1.24.9
removed

2024-07-08 11:33 UTC, satenderrathee commented on cicd/build/azDevOps/azure/pipeline-vars.yml
> +  #   value: acacore
removed

2024-07-08 11:34 UTC, satenderrathee commented on cicd/build/azDevOps/azure/pipeline-vars.yml
> +  #   value: $(company)
done

2024-07-08 11:34 UTC, satenderrathee commented on cicd/build/azDevOps/azure/pipeline-vars.yml
> +  #   value: ed-stacks-nonprod-uks-aca
done

2024-07-08 11:34 UTC, satenderrathee commented on cicd/build/azDevOps/templates/infra-tests.yml
> +  # TF_VAR_resource_group_name:
done

2024-07-08 11:34 UTC, satenderrathee commented on cicd/build/azDevOps/templates/infra-tests.yml
> +      # TF_VAR_resource_group_name: ${{ parameters.TF_VAR_resource_group_name }}
done

2024-07-08 11:34 UTC, satenderrathee commented on cicd/build/config/stage_envvars.yml
> +      #   description: The location/region where the Azure Container Registry (ACR) should be created or where the existing ACR is located.
done

2024-07-08 11:34 UTC, satenderrathee commented on cicd/build/scripts/Deploy-Charts.ps1
done

2024-07-08 11:35 UTC, satenderrathee commented on cicd/build/taskctl/tasks.yaml
> +  #       Invoke-Inspec -execute -arguments "--input-file ${PWD}/inspec_inputs.yml" -path $env:INSPEC_FILES
done

2024-07-08 11:35 UTC, satenderrathee commented on deploy/terraform/azure/outputs.tf
> +# }
done

2024-07-08 11:43 UTC, satenderrathee commented on cicd/build/azDevOps/azure/deploy-infrastructure.yml
> +                    #         AZURE_TENANT_ID: $(azure-tenant-id)
removed

2024-07-08 11:43 UTC, satenderrathee commented on cicd/build/taskctl/tasks copy.yaml
done

2024-07-08 11:43 UTC, satenderrathee commented on src/deploy-aca.yml
> +              #SELF_REPO_SRC: src/app
updated

2024-07-08 11:44 UTC, satenderrathee commented on cicd/build/azDevOps/azure/deploy-infrastructure.yml
> +                    #         AZURE_TENANT_ID: $(azure-tenant-id)
done

2024-07-08 11:45 UTC, satenderrathee commented on deploy/terraform/azure/provider.tf
> +    # key                  = "terraform.tfstate"  # What your state output will be named.
done

2024-07-08 11:50 UTC, satenderrathee commented on src/terraform/outputs.tf
These are App specific Infra , so kept under app, we have used the same approach in stack data project as well. I have mentioned that in agreed ADR as well https://amidodevelopment.atlassian.net/wiki/spaces/TEC/pages/edit-v2/4508418074?draftShareId=74f0c4c4-0ebf-4e5b-94bf-e99d8d8403dd.

2024-07-08 11:50 UTC, satenderrathee commented on src/terraform/main.tf
These are App specific Infra , so kept under app, we have used the same approach in stack data project as well. I have mentioned that in agreed ADR as well https://amidodevelopment.atlassian.net/wiki/spaces/TEC/pages/edit-v2/4508418074?draftShareId=74f0c4c4-0ebf-4e5b-94bf-e99d8d8403dd.

2024-07-08 11:50 UTC, satenderrathee commented on src/terraform/locals.tf
These are App specific Infra , so kept under app, we have used the same approach in stack data project as well. I have mentioned that in agreed ADR as well https://amidodevelopment.atlassian.net/wiki/spaces/TEC/pages/edit-v2/4508418074?draftShareId=74f0c4c4-0ebf-4e5b-94bf-e99d8d8403dd.

2024-07-08 11:51 UTC, satenderrathee commented on src/terraform/data.tf
> +  resource_group_name = var.acr_rg #"aca-test-rg"  module.default_label.id
done

2024-07-08 11:51 UTC, satenderrathee commented on src/terraform/data.tf
These are App specific Infra , so kept under app, we have used the same approach in stack data project as well. I have mentioned that in agreed ADR as well https://amidodevelopment.atlassian.net/wiki/spaces/TEC/pages/edit-v2/4508418074?draftShareId=74f0c4c4-0ebf-4e5b-94bf-e99d8d8403dd.

2024-07-08 12:02 UTC, satenderrathee commented on deploy/terraform/azure/variables.tf
> +}
done

2024-07-08 12:04 UTC, satenderrathee commented on deploy/tests/inspec.lock
added

2024-07-08 12:05 UTC, satenderrathee commented on src/deploy-aca.yml
> +          #     artifactName: docs
removed

2024-07-08 12:06 UTC, satenderrathee commented on src/terraform/.terraform.lock.hcl
added

2024-07-08 12:16 UTC, satenderrathee commented on cicd/build/azDevOps/azure/pipeline-vars.template.yml
done

2024-07-08 12:28 UTC, satenderrathee commented on src/aca-vars.yml
This is app specific variable , we are not targeting Stacks-CLI to output app specific variables . So kept them separate.

2024-07-08 15:22 UTC, satenderrathee commented on cicd/build/azDevOps/azure/deploy-infrastructure.yml
> +          - group: stacks-credentials-nonprod-kv #ensono-sp-creds
done

2024-07-08 15:22 UTC, satenderrathee commented on cicd/build/azDevOps/azure/deploy-infrastructure.yml
> +                      displayName: Set Evn Variables
removed

2024-07-08 15:29 UTC, satenderrathee commented on cicd/build/azDevOps/azure/deploy-infrastructure.yml
> +      - group: amido-stacks-github-credentials   #amido-stacks-webapp
done

2024-07-08 15:34 UTC, satenderrathee commented on src/deploy-aca.yml
> +      - group: stacks-credentials-nonprod-kv
done

2024-07-08 15:34 UTC, satenderrathee commented on src/deploy-aca.yml
> +          - group: stacks-credentials-nonprod-kv #ensono-sp-creds
done

2024-07-08 15:34 UTC, satenderrathee commented on src/deploy-aca.yml
> +                            ARM_CLIENT_SECRET: $(azure-client-secret)
done

2024-07-08 15:34 UTC, satenderrathee commented on src/deploy-aca.yml
> +                            ARM_CLIENT_SECRET: $(azure-client-secret)
done

2024-07-08 15:35 UTC, satenderrathee commented on src/deploy-aca.yml
> +      - group: amido-stacks-github-credentials   #amido-stacks-webapp
done

2024-07-08 15:38 UTC, satenderrathee commented on src/deploy-aca.yml
> +                        TF_VAR_container_app_name: $(container_app_name)
This is app specific variables, we are not targeting Stacks-CLI to output app specific variables .

2024-07-09 07:06 UTC, satenderrathee commented on deploy/tests/controls/resource_group.rb
Done

2024-07-09 07:07 UTC, satenderrathee commented on src/deploy-aca.yml
> +  #   value: accept-silent
Done

2024-07-09 07:07 UTC, satenderrathee commented on src/deploy-aca.yml
> +                    #     TF_VAR_container_app_name: $(container_app_name)
Testing included now

2024-07-09 08:59 UTC, satenderrathee commented on cicd/build/taskctl/tasks.yaml
> +        Invoke-Inspec -execute -arguments "--input-file ${PWD}/inspec_inputs.yml" -path $env:INSPEC_FILES
I appreciate the insight from your Redis feature tasks. For now, I'd like to keep the current structure as it aligns well with our existing patterns and meets our needs effectively. I'll keep your approach in mind for future optimizations.

2024-07-09 09:06 UTC, satenderrathee commented
> Good overall work, some rethinking required around directory structure and redundant variable files. Lots of left over comments to remove and a few lock files.
> 
> Needs some decent documentation within the repo to support the feature outlining: Why are we doing this feature? How do you use this feature? What is the pipeline doing? What are the tests doing?

Thanks Dan for the review. I have actioned the review comments now.
I don't think the repo documentation is in the scope of current story but I will add the task for it and will action this in a separate PR.

2024-07-09 10:30 UTC, danEnsono requested changes
All good except one of the test names, fix that and good to go!

2024-07-09 10:30 UTC, danEnsono commented on deploy/tests/controls/acae.rb
Typo in the name?

2024-07-09 10:45 UTC, satenderrathee commented on deploy/tests/controls/acae.rb
updated the name :)

2024-07-09 10:53 UTC, danEnsono approved these changes
Good to go!

2024-07-09 10:53 UTC, danEnsono approved these changes

2024-07-09 11:01 UTC, merged